title: SDM234 · Fall 2026
description: Course materials for SDM234, Fall 2026
theme: just-the-docs

url: https://wavelix.github.io
repository: Wavelix/SDM234-26Fall

aux_links:
  GitHub Repository: https://github.com/Wavelix/SDM234-26Fall
